version: '3.7'

services:
  openldap:
    container_name: openldap
    build:
      context: ./
      dockerfile: Dockerfile_ldap
      network: host
    command: "--copy-service --loglevel debug"
    tty: true
    stdin_open: true
    volumes:
      - ./certs:/container/service/slapd/assets/certs/:ro
      # - ./db:/var/lib/ldap
      # - ./slapd.d:/etc/ldap/slapd.d
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - "389:389"
      - "636:636"
    # For replication to work correctly, domainname and hostname must be
    # set correctly so that "hostname"."domainname" equates to the
    # fully-qualified domain name for the host.
    domainname: "awas.lab"
    hostname: "openldap"
  phpldapadmin:
    image: osixia/phpldapadmin:latest
    container_name: phpldapadmin
    environment:
      PHPLDAPADMIN_LDAP_HOSTS: "openldap"
      PHPLDAPADMIN_HTTPS: "false"
    ports:
      - "18080:80"
    depends_on:
      - openldap
  eapttsl:
    container_name: radius-eap-ttls
    build:
      context: ./
      dockerfile: Dockerfile_radius
      network: host
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    ports:
      - 1812:1812/udp
    dns_search: .
    depends_on:
      - openldap
