version: '3.8'
services:
  freeradius:
    image: freeradius/freeradius-server:latest
    container_name: freeradius
    ports:
      - "1812:1812/udp"
      - "1813:1813/udp"
    volumes:
      - ./radius-config:/etc/freeradius/3.0
    command: ["-X"]
    environment:
      - "FREERADIUS_LOG_LEVEL=info"